# Generated by Django 3.2.3 on 2021-05-27 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SomeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_1', models.CharField(max_length=100)),
                ('field_2', models.CharField(max_length=100)),
                ('field_3', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'SomeModel',
                'verbose_name_plural': 'SomeModels',
            },
        ),
    ]
